### ISSUE TITLE
Durable stream causes NATS timeouts if stream is full

### ISSUE THREAD

**Issue by eoneal89** [nats-io/jetstream#396]
If a stream reaches its max byte capacity, NATS will start throwing errors if a client tries to publish to the subject being consumed by the stream. After the stream dies, `nats stream info` responds with `nats: error: could not request Stream info: context deadline exceeded`. Restarting the server restores the ability to see the stream info, but dies immediately again when publishing.

Steps to reproduce:
Stream configuration:
```
Configuration:

             Subjects: *.*.test.>
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: 48 MiB
          Maximum Age: 0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited
```

On the box: `nats bench --ack --size=512 --pub=10 test.test.test.test`

After the stream fills up the tests start to throw timeouts.

This was run on the most current nightly docker image (nightly-20201201). I ran it against the nightly image from October that we had previously been testing against (nightly-20201023), and the bug did not occur.

**Comment by ripienaar** [comment]
I can recreate this problem easily using `nats bench`.

Looking at a stack trace at the time after I did a stream info on the locked up stream, I see the below, so I think there's a deadlock:

/cc @derekcollison 

```
goroutine 1258 [semacquire, 2 minutes]:
sync.runtime_SemacquireMutex(0xc00019284c, 0x0, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:50
github.com/nats-io/nats-server/v2/server.(*Stream).storeUpdates(0xc000192840, 0xffffffffffffffff, 0xffffffffffffff55, 0x1, 0xc000023a40, 0xd)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/stream.go:783 +0x177
github.com/nats-io/nats-server/v2/server.(*fileStore).removeMsg(0xc00020e540, 0x1, 0x0, 0xc0000238c0, 0xd, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/filestore.go:948 +0x33c
github.com/nats-io/nats-server/v2/server.(*fileStore).deleteFirstMsgLocked(0xc00020e540, 0x164ce61d93d66100, 0x0, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/filestore.go:787 +0x7d
github.com/nats-io/nats-server/v2/server.(*fileStore).enforceBytesLimit(0xc00020e540)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/filestore.go:779 +0x42
github.com/nats-io/nats-server/v2/server.(*fileStore).StoreMsg(0xc00020e540, 0xc0000238c0, 0xd, 0x0, 0x0, 0x0, 0xc00002633e, 0x80, 0xc2, 0x3b, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/filestore.go:684 +0x35f
github.com/nats-io/nats-server/v2/server.(*Stream).processInboundJetStreamMsg(0xc000192840, 0xc0001e98c0, 0xc000145300, 0xc0000238c0, 0xd, 0xc0000a16b0, 0x26, 0xc00002633e, 0x80, 0xc2)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/stream.go:1046 +0x527
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc000145300, 0xc0001e98c0, 0xc000026304, 0xd, 0xfc, 0xc000026312, 0x26, 0xee, 0xc000146759, 0x40, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:2966 +0x352
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc000145300, 0xc00000a960, 0xc000085ec0, 0xc00002633e, 0x82, 0xc2, 0x0, 0x0, 0x0, 0xc000026304, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3764 +0x603
github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0xc000145300, 0xc00002633e, 0x82, 0xc2, 0xc7)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3390 +0x3b6
github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg(0xc000145300, 0xc00002633e, 0x82, 0xc2)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3261 +0x95
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc000145300, 0xc000026300, 0xc0, 0x100, 0xc0, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/parser.go:461 +0x23a5
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc000145300, 0x0, 0x0, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:1052 +0x547
github.com/nats-io/nats-server/v2/server.(*Server).createClient.func2()
        /Users/rip/go/src/github.com/nats-io/nats-server/server/server.go:2252 +0x45
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
        /Users/rip/go/src/github.com/nats-io/nats-server/server/server.go:2627 +0xc1
```

and later

```
goroutine 1362 [semacquire, 2 minutes]:
sync.runtime_SemacquireMutex(0xc00019284c, 0xc00020c000, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:50
github.com/nats-io/nats-server/v2/server.(*Stream).Created(0xc000192840, 0xc0000a67f4, 0x7, 0xc000192840)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/stream.go:388 +0xbd
github.com/nats-io/nats-server/v2/server.(*Server).jsStreamInfoRequest(0xc00018e000, 0xc0001b3ce0, 0xc000254000, 0xc0000a67e0, 0x1b, 0xc0000a6800, 0x11, 0xc000191a4a, 0x0, 0x1b6)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/jetstream_api.go:955 +0x573
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc000254000, 0xc0001b3ce0, 0xc00015f118, 0x1b, 0x20, 0xc0000a67a0, 0x11, 0x20, 0xc000255459, 0x38, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:2966 +0x352
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc000254000, 0xc00000ad20, 0xc0001f1050, 0xc000191a4a, 0x2, 0x1b6, 0x0, 0x0, 0x0, 0xc00015f118, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3764 +0x603
github.com/nats-io/nats-server/v2/server.(*client).processServiceImport(0xc000254000, 0xc000180a00, 0xc00000a960, 0xc000191a4a, 0x2, 0x1b6)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3582 +0x906
github.com/nats-io/nats-server/v2/server.(*Account).addServiceImportSub.func1(0xc0001e8dc0, 0xc000254000, 0xc0000a6740, 0x1b, 0xc0012ec270, 0x26, 0xc000191a4a, 0x2, 0x1b6)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/accounts.go:1752 +0x5e
github.com/nats-io/nats-server/v2/server.(*client).deliverMsg(0xc000254000, 0xc0001e8dc0, 0xc000191a04, 0x1b, 0x1fc, 0xc000191a20, 0x26, 0x1e0, 0xc000255459, 0x4d, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:2964 +0x45f
github.com/nats-io/nats-server/v2/server.(*client).processMsgResults(0xc000254000, 0xc00000a960, 0xc0001f1020, 0xc000191a4a, 0x2, 0x1b6, 0x0, 0x0, 0x0, 0xc000191a04, ...)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3764 +0x603
github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg(0xc000254000, 0xc000191a4a, 0x2, 0x1b6, 0x1b9)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3390 +0x3b6
github.com/nats-io/nats-server/v2/server.(*client).processInboundMsg(0xc000254000, 0xc000191a4a, 0x2, 0x1b6)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:3261 +0x95
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc000254000, 0xc000191a00, 0x4c, 0x200, 0x4c, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/parser.go:461 +0x23a5
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc000254000, 0x0, 0x0, 0x0)
        /Users/rip/go/src/github.com/nats-io/nats-server/server/client.go:1052 +0x547
github.com/nats-io/nats-server/v2/server.(*Server).createClient.func2()
        /Users/rip/go/src/github.com/nats-io/nats-server/server/server.go:2252 +0x45
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
        /Users/rip/go/src/github.com/nats-io/nats-server/server/server.go:2627 +0xc1
```

**Comment by derekcollison** [comment]
Will take a look and fix. Thanks.

**Comment by derekcollison** [comment]
Fixed, sorry for the inconvenience.. You should be good to go again.

**Comment by ripienaar** [comment]
Looks good on a new stream.

The stream that previously got stuck due to this bug remains broken though, I have to drop that stream and make it new to continue, not the end of the world in this case but thought it worth mentioning in case there's something there we want to look at @derekcollison

**Comment by derekcollison** [comment]
Backup the filestore and send to me if you can.

**Comment by eoneal89** [comment]
Thanks!
